name: CI

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

on: 
  workflow_dispatch:
    inputs:
      activate-unity:
        description: 'Publish to Beta'
        required: false

jobs:
  build:
    name: Build my project
    runs-on: ubuntu-latest
    steps:
        # Checkout 
        - name: Checkout repository
          uses: actions/checkout@v2
          with:
            lfs: true
            
        #- name: Delete lfs files
        #  shell: bash
        #  run: |
        #    echo "Before" && \
        #    ls ./Assets/Thirdparty/ && \
        #    rm ./Assets/Thirdparty/*.TGA && \
        #    rm ./Assets/Thirdparty/*.TGA.meta && \
        #    echo "After"
        #    ls ./Assets/Thirdparty/
        
        # Cache
        #- uses: actions/cache@v1.1.0
        #  with:
        #    path: ./Library
        #    key: Library-unity-ci-WebGL
        #    restore-keys: |
        #      Library-unity-ci-
        #      Library-
            
        # Test
        #- name: Unity - Test runner
        #  uses: game-ci/unity-test-runner@v2.0-alpha-2
        #  env:
        #    UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        #  with:
        #    unityVersion: 2020.2.2f1
            
        # Build
        - name: Unity - Builder
          uses: game-ci/unity-builder@v2.0-alpha-6
          env:
            UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          with:
            unityVersion: 2020.2.2f1
            targetPlatform: StandaloneWindows64
            allowDirtyBuild: true
        
        # Setup steamcmd
        - name: Setup steamcmd
          uses: CyberAndrii/setup-steamcmd@v1.1.1
          
        - name: Write release.vdf
          run: |
            cat << EOF > $GITHUB_WORKSPACE/release.vdf
              "AppBuild"
              {
                "AppID" "1891530" // Your AppID
                "Desc" "descrt"

                "SetLive" "test"

                "ContentRoot" "./"
                "BuildOutput" "build/"

                "Depots"
                {
                  "1891532"
                  {
                    "ContentRoot" "./build"
                    "FileMapping"
                    {
                      "LocalPath" "*"
                      "DepotPath" "."
                      "recursive" "1"
                    }
                  }
                }
              }

          
            cat $GITHUB_WORKSPACE/release.vdf
      
        - uses: game-ci/steam-deploy@v1
          with:
            username: ${{ secrets.STEAM_USERNAME }}
            password: ${{ secrets.STEAM_PASSWORD }}
            configVdf: ${{ secrets.STEAM_CONFIG_VDF}}
            ssfnFileName: ${{ secrets.STEAM_SSFN_FILE_NAME }}
            ssfnFileContents: ${{ secrets.STEAM_SSFN_FILE_CONTENTS }}
            appId: 1891530
            buildDescription: v1.2.3
            rootPath: build
            depot1Path: StandaloneWindows64
            releaseBranch: test

      
        # Output
        - uses: actions/upload-artifact@v1
          with:
            name: Build
            path: build
